version: 0.2

phases:
  install:
    commands:
      - echo "Fetching the PEM file from Secrets Manager"
      - aws secretsmanager get-secret-value --secret-id cap/uat/credentials --query 'SecretString' --output text | jq -r '.["cap-uat-key-pair"]' > /tmp/cap-uat-key-pair.pem
      - chmod 400 /tmp/cap-uat-key-pair.pem

  build:
    commands:
      - echo "Building the project..."
      - mvn clean install

  post_build:
    commands:
      - echo "Copying JAR to EC2..."
      - scp -o StrictHostKeyChecking=no -i /tmp/cap-uat-key-pair.pem target/*.jar ubuntu@18.61.21.68:/opt/cap/cap-backend-uat.jar
      - echo "Running JAR on EC2..."
      - |
        ssh -o StrictHostKeyChecking=no -i /tmp/cap-uat-key-pair.pem ubuntu@18.61.21.68 << 'EOF'
          pkill -f "java -jar" || true
          nohup java -jar /opt/cap/cap-backend-uat.jar > /opt/cap/app.log 2>&1 &
        EOF
