apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meritcap-backend-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - api.meritcap.com
      secretName: cloudflare-tls
  rules:
    - host: api.meritcap.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meritcap-backend-svc
                port:
                  number: 8080
