# UAT database configuration

spring:
  datasource:
    url: jdbc:mysql://82.112.234.51:3306/cap_uat?allowPublicKeyRetrieval=true&useSSL=false&createTableIfNotExists=true
    username: cap_uat
    password: w4JU)ZNlS!0T!B6
  jpa:
    hibernate:
      ddl-auto: update

aws:
  cognito:
    userPoolId: ap-south-2_O8GKQAlPb
    clientId: 1l642vjbnc4qfflhlfrt1sbbcl
    clientSecret: 1mdallivtrvo4ap97u7597vdiqdcm3cbekaqiv7m8f0dbtuoom7g
  region: ap-south-2
  s3:
    bucketName: career-adivce-partner

logging:
  level:
    root: INFO
    com.consultancy.education: DEBUG  # Enable DEBUG logs for this package
    org.springframework: WARN         # Reduce logs for Spring framework
