spring:
  application:
    name: meritcap-backend

  jackson:
    date-format: dd/MM/yyyy

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: dev

server:
  servlet:
    context-path: /api
