# UAT database configuration

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

aws:
  cognito:
    userPoolId: ${COGNITO_USER_POOL_ID}
    clientId: ${COGNITO_CLIENT_ID}
    clientSecret: ${COGNITO_CLIENT_SECRET}
  s3:
    bucketName: ${S3_BUCKET_NAME}
    accessKeyId: ${IAM_DRUVA_CAP_ACCESS_KEY_ID}
    secretAccessKey: ${IAM_DRUVA_CAP_SECRET_ACCESS_KEY}
  region: ap-south-2
  secret:
    names: cap/uat/credentials

logging:
  level:
    root: INFO
    com.consultancy.education: DEBUG  # Enable DEBUG logs for this package
    org.springframework: WARN         # Reduce logs for Spring framework
