apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meritcap-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
spec:
  ingressClassName: public
  tls:
    - hosts:
        - meritcap.com
        - admin.meritcap.com
        - api.meritcap.com
      secretName: cloudflare-tls
  rules:
    - host: meritcap.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meritcap-user-svc
                port:
                  number: 3000
    - host: admin.meritcap.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meritcap-admin-svc
                port:
                  number: 3000
    - host: api.meritcap.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meritcap-backend-svc
                port:
                  number: 8080
